### ISSUE TITLE
[KeyboardClick] question: how to get all sounds from Opera GX

### ISSUE THREAD

**Issue by Davilarek** [SpoonMcForky/BetterDiscordPlugins#4]
Hi, I'm porting your plugin into Chromium browser (for myself only), and I would like to know how you got these sounds from Opera GX

**Comment by SpoonMcForky** [comment]
> Hi, I'm porting your plugin into Chromium browser (for myself only), and I would like to know how you got these sounds from Opera GX

Very painfully. First I tried seeing if I could just get them straight from the browser but I gave up on that for some reason (I can't remember exactly but I remember spending a while on it) so I just used Voicemeeter to record audio losslessly and then took samples of each click sound. I then imported them into FlStudio (I just had it downloaded and it worked fine but you could probably use audacity or another program) and isolated each sound as best as I could within the limitations of the software, so that there was no added time at the end or the beginning of the sound. I have all of the files if you want them.
Also, I was going to port this to a browser extension anyway but I just haven't had the time or motivation, so you may see that in the future. No promises,though.

**Comment by Davilarek** [comment]
Thanks for explanation. I think I will stay only with these clicking sounds for now. I'm closing this because you answered my question. Thanks again.
